spring:
    application:
        name: microservice
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${DB_URL:jdbc:postgresql://localhost:5432/cart_db}
        username: ${DB_USER:postgres}
        password: ${DB_PASSWORD:postgres}
        hikari:
            maximum-pool-size: 10